swagger: "2.0"
consumes:
- application/json
produces:
- application/json
x-gw-combine:
- gw.core.cc.systemtools.v1.systemtools_core-1.0
x-gw-schema-import:
  systemtools: gw.content.cc.systemtools.v1.systemtools_content-1.0
paths: {}