swagger: "2.0"
consumes:
- application/json
produces:
- application/json
x-gw-combine:
- gw.core.cc.claim.v1.claim_auto_core-1.0
- ext.claim.v1.claim_ext-1.0
x-gw-schema-import:
  claims: ext.claim.v1.claim_auto_ext-1.0
paths: {}