swagger: "2.0"
consumes:
- application/json
produces:
- application/json
x-gw-combine:
- gw.content.cc.claim.v1.claim_content-1.0
x-gw-schema-import:
  claims: ext.claim.v1.claim_ext-1.0
x-gw-apihandlers:
- gw.rest.ext.cc.claim.v1.ClaimApiExtHandler
paths: {}