swagger: "2.0"
info:
  title: "ClaimCenter Common API"
x-gw-combine:
- gw.core.pl.common.v1.common_pl-1.0
- gw.core.cc.framework.v1.framework_core-1.0
x-gw-schema-import:
  common: gw.core.cc.common.v1.common_core-1.0
x-gw-apihandlers:
- gw.rest.core.cc.common.v1.CommonApiCoreHandler
paths: {}
x-gw-cors-policy: common