resources:
  TestUtilContacts:
    permissions:
      view: true
      create: true
    filter: __noFilter
  TestUtilGroups:
    permissions:
      view: true
      create: true
    filter: __noFilter
  TestUtilOpenApiSchema:
    permissions:
      view: true
  TestUtilPolicies:
    permissions:
      view: true
      create: true
    filter: __noFilter
  TestUtilSpecialistService:
    permissions:
      view: true
  TestUtilSpecialistServices:
    permissions:
      view: true
      create: true
    filter: __noFilter
  TestUtilUsers:
    permissions:
      view: true
      create: true
    filter: __noFilter