resources:
  TestUtilContact:
    resource: gw.rest.core.cc.testutil.v1.contact.TestUtilContactCoreResource
  TestUtilContacts:
    resource: gw.rest.core.cc.testutil.v1.contact.TestUtilContactsCoreResource
  TestUtilGroup:
    resource: gw.rest.core.cc.testutil.v1.group.TestUtilGroupCoreResource
  TestUtilGroups:
    resource: gw.rest.core.cc.testutil.v1.group.TestUtilGroupsCoreResource
  TestUtilOpenApiSchema:
    resource: gw.api.modules.rest.framework.v1.openapi.v3.OpenApiJsonPlatformResource
  TestUtilPolicies:
    resource: gw.rest.core.cc.testutil.v1.policy.TestUtilPoliciesCoreResource
  TestUtilPolicy:
    resource: gw.rest.core.cc.testutil.v1.policy.TestUtilPolicyCoreResource
  TestUtilSpecialistService:
    resource: gw.rest.core.cc.testutil.v1.servicerequest.TestUtilSpecialistServiceCoreResource
  TestUtilSpecialistServices:
    resource: gw.rest.core.cc.testutil.v1.servicerequest.TestUtilSpecialistServicesCoreResource
  TestUtilUser:
    resource: gw.rest.core.cc.testutil.v1.user.TestUtilUserCoreResource
  TestUtilUsers:
    resource: gw.rest.core.cc.testutil.v1.user.TestUtilUsersCoreResource
basePaths:
  test-util: /test-util/v1
mappingFiles:
- gw.core.cc.testutil.v1.testutil_core-1.0
updaterFiles:
- gw.core.cc.testutil.v1.testutil_core-1.0
resourceAccess:
  internal:
    yaml: gw.core.cc.testutil.v1.internal_core-1.0
  service:
    yaml: gw.core.cc.testutil.v1.serviceUser_core-1.0
  unauthenticated:
    yaml: gw.core.cc.testutil.v1.unauthenticatedUser_core-1.0