swagger: "2.0"
consumes:
- application/json
produces:
- application/json
x-gw-combine:
- gw.content.cc.systemtools.v1.systemtools_content-1.0
x-gw-schema-import:
  systemtools: ext.systemtools.v1.systemtools_ext-1.0
x-gw-apihandlers:
- gw.rest.ext.cc.systemtools.v1.SystemToolsApiExtHandler
paths: {}