swagger: "2.0"
consumes:
- application/json
produces:
- application/json
x-gw-combine:
- gw.core.cc.admin.v1.admin_core-1.0
x-gw-schema-import:
  admin: gw.content.cc.admin.v1.admin_content-1.0
paths: {}