package gw.rest.ext.cc.claim.property.v1.claims.policy.locationbasedriskunits.coverages

uses gw.rest.core.cc.claim.property.v1.claims.policy.locationbasedriskunits.coverages.UnverifiedLocationBasedRiskUnitCoveragesCoreResource

@Export
class UnverifiedLocationBasedRiskUnitCoveragesExtResource extends UnverifiedLocationBasedRiskUnitCoveragesCoreResource {
}