swagger: "2.0"
info:
  title: "ClaimCenter System Tools API"
x-gw-combine:
- gw.core.pl.systemtools.v1.systemtools_pl-1.0
- gw.core.cc.framework.v1.framework_core-1.0
x-gw-schema-import:
  systemtools: gw.core.cc.systemtools.v1.systemtools_core-1.0
x-gw-apihandlers:
- gw.rest.core.cc.systemtools.v1.SystemToolsApiCoreHandler
paths: {}
x-gw-cors-policy: systemtools