resources:
  Activities:
    permissions:
      view: true
    filter: __noFilter
  Activity:
    permissions:
      view: true
      edit: true
      approve: true
      assign: true
      complete: true
      reject: true
      skip: true
  ActivityAssignees:
    permissions:
      view: true
  ActivityNotes:
    permissions:
      view: true
      create: true
    filter: __noFilter
  ActivityPattern:
    permissions:
      view: true
  AdminOpenApiSchema:
    permissions:
      view: true
  AssessmentContentItem:
    permissions:
      view: true
      edit: true
      delete: true
  AssessmentContentItems:
    permissions:
      view: true
      create: true
    filter: __noFilter
  AssessmentSummaries:
    permissions:
      view: true
      create: true
    filter: __noFilter
  AssessmentSummary:
    permissions:
      view: true
  AssignableQueue:
    permissions:
      view: true
      edit: true
      delete: true
  AssignableQueues:
    permissions:
      view: true
      create: true
    filter: __noFilter
  Assignee:
    permissions:
      view: true
  Attribute:
    permissions:
      view: true
      edit: true
      delete: true
  Attributes:
    permissions:
      view: true
      create: true
    filter: __noFilter
  AuthorityLimit:
    permissions:
      view: true
      edit: true
      delete: true
  AuthorityLimitProfile:
    permissions:
      view: true
      edit: true
      delete: true
  AuthorityLimitProfiles:
    permissions:
      view: true
      create: true
    filter: __noFilter
  AuthorityLimits:
    permissions:
      view: true
      create: true
    filter: __noFilter
  BaggageIncident:
    permissions:
      view: true
      edit: true
      delete: true
  BodilyInjuryPoint:
    permissions:
      view: true
      edit: true
      delete: true
  BodilyInjuryPoints:
    permissions:
      view: true
      create: true
    filter: __noFilter
  BusinessLineMetadataSchema:
    permissions:
      view: true
  CalendarDateCalculation:
    permissions:
      view: true
      edit: true
      calculate-date: true
  Catastrophe:
    permissions:
      view: true
      edit: true
      delete: true
  CatastrophePeril:
    permissions:
      view: true
      edit: true
      delete: true
  CatastrophePerils:
    permissions:
      view: true
      create: true
  CatastropheZone:
    permissions:
      view: true
      edit: true
      delete: true
  CatastropheZones:
    permissions:
      view: true
      create: true
  Catastrophes:
    permissions:
      view: true
      create: true
    filter: __noFilter
  Check:
    permissions:
      view: true
      edit: true
      delete: true
      acknowledge-submission: true
      mark-cleared: true
      mark-issued: true
      mark-stopped: true
      mark-voided: true
      request-stop: true
      request-void: true
  CheckSet:
    permissions:
      view: true
  CheckSets:
    permissions:
      view: true
      create: true
    filter: __noFilter
  Checks:
    permissions:
      view: true
    filter: __noFilter
  Claim:
    permissions:
      view: true
      edit: true
      assign: true
      cancel: true
      close: true
      reopen: true
      submit: true
      validate: true
  ClaimActivities:
    permissions:
      view: true
      create: true
    filter: __noFilter
  ClaimActivityAssignees:
    permissions:
      view: true
  ClaimActivityPatterns:
    permissions:
      view: true
  ClaimApiOpenApiSchema:
    permissions:
      view: true
  ClaimBaggageIncidents:
    permissions:
      view: true
      create: true
    filter: __noFilter
  ClaimContact:
    permissions:
      view: true
      edit: true
      delete: true
      initialize-authorization-id: true
  ClaimContactRoleOwners:
    permissions:
      view: true
  ClaimContacts:
    permissions:
      view: true
      create: true
    filter: __noFilter
  ClaimDocument:
    permissions:
      view: true
      edit: true
      delete: true
  ClaimDocumentContent:
    permissions:
      view: true
  ClaimDocuments:
    permissions:
      view: true
      create: true
    filter: __noFilter
  ClaimDwellingIncidents:
    permissions:
      view: true
      create: true
    filter: __noFilter
  ClaimExposures:
    permissions:
      view: true
      create: true
    filter: __noFilter
  ClaimFixedPropertyIncidents:
    permissions:
      view: true
      create: true
    filter: __noFilter
  ClaimGeneralIncidents:
    permissions:
      view: true
      create: true
    filter: __noFilter
  ClaimGraphSchema:
    permissions:
      view: true
  ClaimHistoryEvents:
    permissions:
      view: true
    filter: __noFilter
  ClaimInfo:
    permissions:
      view: true
      edit: false
      retrieve: true
  ClaimInfos:
    permissions:
      view: true
    filter: __noFilter
  ClaimInjuryIncidents:
    permissions:
      view: true
      create: true
    filter: __noFilter
  ClaimIntakeInteractions:
    permissions:
      view: true
      create: true
    filter: __noFilter
  ClaimLivingExpensesIncidents:
    permissions:
      view: true
      create: true
    filter: __noFilter
  ClaimMatters:
    permissions:
      view: true
      create: true
    filter: __noFilter
  ClaimNotes:
    permissions:
      view: true
      create: true
    filter: __noFilter
  ClaimOtherStructureIncidents:
    permissions:
      view: true
      create: true
    filter: __noFilter
  ClaimPropertyContentsIncidents:
    permissions:
      view: true
      create: true
    filter: __noFilter
  ClaimRelatedObjects:
    permissions:
      view: true
  ClaimSearch:
    permissions:
      view: true
    filter: __noFilter
  ClaimSearchResult:
    permissions:
      view: true
  ClaimSearchResultWrapper:
    permissions:
      view: true
  ClaimSearchV2:
    permissions:
      view: true
  ClaimServiceRequests:
    permissions:
      view: true
      create: true
    filter: __noFilter
  ClaimSolrSearch:
    permissions:
      view: true
  ClaimSolrSearchResult:
    permissions:
      view: true
  ClaimTripIncidents:
    permissions:
      view: true
      create: true
    filter: __noFilter
  ClaimVehicleIncidents:
    permissions:
      view: true
      create: true
    filter: __noFilter
  Claims:
    permissions:
      view: true
      create: true
    filter: __noFilter
  CommonOpenApiSchema:
    permissions:
      view: true
  ContactRoleConstraint:
    permissions:
      view: true
  ContactRoleConstraints:
    permissions:
      view: true
  # override common_pl
  Document:
    permissions:
      view: true
      edit: true
      delete: true
  DocumentContent:
    permissions:
      view: true
  DwellingIncident:
    permissions:
      view: true
      edit: true
      delete: true
  Endorsement:
    permissions:
      view: true
  EntitySchema:
    permissions:
      view: true
  EntitySchemas:
    permissions:
      view: true
  Exposure:
    permissions:
      view: true
      edit: true
      delete: true
      assign: true
      close: true
      reopen: true
      validate: true
  FinancialCalculation:
    permissions:
      view: true
      edit: true
      get-amount: true
  FinancialCalculations:
    permissions:
      view: true
  FixedPropertyIncident:
    permissions:
      view: true
      edit: true
      delete: true
  GeneralIncident:
    permissions:
      view: true
      edit: true
      delete: true
  GenericRelation:
    permissions:
      view: true
  GeographicZone:
    permissions:
      view: true
  GeographicZones:
    permissions:
      view: true
    filter: __noFilter
  Group:
    permissions:
      view: true
      edit: true
      delete: true
  GroupRegion:
    permissions:
      view: true
      edit: true
      delete: true
  GroupRegions:
    permissions:
      view: true
      create: true
    filter: __noFilter
  GroupUser:
    permissions:
      view: true
      edit: true
      delete: true
  GroupUsers:
    permissions:
      view: true
      create: true
    filter: __noFilter
  Groups:
    permissions:
      view: true
      create: true
    filter: __noFilter
  HistoryEvent:
    permissions:
      view: true
  Holiday:
    permissions:
      view: true
      edit: true
      delete: true
  HolidayZone:
    permissions:
      view: true
      edit: true
      delete: true
  HolidayZones:
    permissions:
      view: true
      create: true
    filter: __noFilter
  Holidays:
    permissions:
      view: true
      create: true
    filter: __noFilter
  ICDCode:
    permissions:
      view: true
      edit: true
  ICDCodeSearch:
    permissions:
      view: true
    filter: __noFilter
  ICDCodes:
    permissions:
      view: true
      create: true
    filter: __noFilter
  InjuryIncident:
    permissions:
      view: true
      edit: true
      delete: true
  IntakeInteraction:
    permissions:
      view: true
      edit: true
  LivingExpensesIncident:
    permissions:
      view: true
      edit: true
      delete: true
  LocationBasedRiskUnit:
    permissions:
      view: true
  LocationBasedRiskUnitCoverage:
    permissions:
      view: __inherit
  LocationBasedRiskUnitCoverages:
    permissions:
      view: __inherit
    filter: __noFilter
  LocationBasedRiskUnits:
    permissions:
      view: true
    filter: __noFilter
  Matter:
    permissions:
      view: true
      edit: true
      assign: true
      close: true
      reopen: true
  MedicalDiagnoses:
    permissions:
      view: true
      create: true
    filter: __noFilter
  MedicalDiagnosis:
    permissions:
      view: true
      edit: true
      delete: true
  MedicalTreatment:
    permissions:
      view: true
      edit: true
      delete: true
  MedicalTreatments:
    permissions:
      view: true
      create: true
  # override common_pl
  Note:
    permissions:
      view: true
      edit: true
      delete: true
  OtherStructureIncident:
    permissions:
      view: true
      edit: true
      delete: true
  Payment:
    permissions:
      view: true
      edit: true
      acknowledge-submission: true
  Payments:
    permissions:
      view: true
    filter: __noFilter
  Policy:
    permissions:
      view: true
  PolicyCoverage:
    permissions:
      view: true
  PolicyCoverages:
    permissions:
      view: true
    filter: __noFilter
  PolicyEndorsements:
    permissions:
      view: true
    filter: __noFilter
  PolicyLocation:
    permissions:
      view: true
  PolicyLocations:
    permissions:
      view: true
    filter: __noFilter
  PropertyContentsIncident:
    permissions:
      view: true
      edit: true
      delete: true
  PropertyContentsScheduledItem:
    permissions:
      view: true
      edit: true
      delete: true
  PropertyContentsScheduledItems:
    permissions:
      view: true
      create: true
    filter: __noFilter
  PropertyItem:
    permissions:
      view: true
  PropertyItems:
    permissions:
      view: true
    filter: __noFilter
  Recoveries:
    permissions:
      view: true
    filter: __noFilter
  Recovery:
    permissions:
      view: true
      edit: true
      acknowledge-submission: true
  RecoveryReserve:
    permissions:
      view: true
      edit: true
      acknowledge-submission: true
  RecoveryReserveSet:
    permissions:
      view: true
  RecoveryReserveSets:
    permissions:
      view: true
      create: true
    filter: __noFilter
  RecoveryReserves:
    permissions:
      view: true
    filter: __noFilter
  RecoverySet:
    permissions:
      view: true
  RecoverySets:
    permissions:
      view: true
      create: true
    filter: __noFilter
  Region:
    permissions:
      view: true
      edit: true
      delete: true
  RegionZone:
    permissions:
      view: true
      edit: true
      delete: true
  RegionZones:
    permissions:
      view: true
      create: true
    filter: __noFilter
  Regions:
    permissions:
      view: true
      create: true
    filter: __noFilter
  Reserve:
    permissions:
      view: true
      edit: true
      acknowledge-submission: true
  ReserveSet:
    permissions:
      view: true
  ReserveSets:
    permissions:
      view: true
      create: true
    filter: __noFilter
  Reserves:
    permissions:
      view: true
    filter: __noFilter
  RiskUnitCoverage:
    permissions:
      view: __inherit
  RiskUnitCoverages:
    permissions:
      view: __inherit
    filter: __noFilter
  Role:
    permissions:
      view: true
      edit: true
      delete: true
  RolePermission:
    permissions:
      view: true
      edit: true
      delete: true
  RolePermissions:
    permissions:
      view: true
      create: true
    filter: __noFilter
  Roles:
    permissions:
      view: true
      create: true
    filter: __noFilter
  SecurityZone:
    permissions:
      view: true
      edit: true
      delete: true
  SecurityZones:
    permissions:
      view: true
      create: true
    filter: __noFilter
  ServiceRequest:
    permissions:
      view: true
      edit: true
      accept: true
      add-quote: true
      approve-quote: true
      assign: true
      cancel: true
      complete-work: true
      decline: true
      internal-cancel: true
      submit: true
  ServiceRequestHistories:
    permissions:
      view: true
  ServiceRequestHistory:
    permissions:
      view: true
  ServiceRequestInvoice:
    permissions:
      view: true
      edit: true
      approve: true
      mark-as-paid: true
      withdraw: true
  ServiceRequestInvoices:
    permissions:
      view: true
      create: true
    filter: __nofilter
  ServiceRequestMessage:
    permissions:
      view: true
  ServiceRequestMessages:
    permissions:
      view: true
      create: true
  ServiceRequests:
    permissions:
      view: true
    filter: __noFilter
  Subrogation:
    permissions:
      view: true
      edit: true
      delete: true
  SubrogationSummaries:
    permissions:
      view: true
      create: true
  SubrogationSummary:
    permissions:
      view: true
      edit: true
  Subrogations:
    permissions:
      view: true
      create: true
  TripAccommodation:
    permissions:
      view: true
      edit: true
      delete: true
  TripAccommodations:
    permissions:
      view: true
      create: true
    filter: __noFilter
  TripIncident:
    permissions:
      view: true
      edit: true
      delete: true
  TripRiskUnit:
    permissions:
      view: true
  TripRiskUnits:
    permissions:
      view: true
    filter: __noFilter
  TripSegment:
    permissions:
      view: true
      edit: true
      delete: true
  TripSegments:
    permissions:
      view: true
      create: true
    filter: __noFilter
  TypeList:
    permissions:
      view: true
  TypeLists:
    permissions:
      view: true
  UnverifiedEndorsement:
    permissions:
      view: __inherit
      edit: __inherit
  UnverifiedLocationBasedRiskUnit:
    permissions:
      view: __inherit
      edit: __inherit
  UnverifiedLocationBasedRiskUnitCoverage:
    permissions:
      view: __inherit
      edit: __inherit
  UnverifiedLocationBasedRiskUnitCoverages:
    permissions:
      view: __inherit
      create: __inherit
    filter: __noFilter
  UnverifiedLocationBasedRiskUnits:
    permissions:
      view: __inherit
      create: __inherit
    filter: __noFilter
  UnverifiedPolicies:
    permissions:
      view: true
      create: true
    filter: __noFilter
  UnverifiedPolicy:
    permissions:
      view: true
      edit: true
  UnverifiedPolicyContacts:
    permissions:
      view: __inherit
      create: __inherit
    filter: __noFilter
  UnverifiedPolicyCoverage:
    permissions:
      view: __inherit
      edit: __inherit
  UnverifiedPolicyCoverages:
    permissions:
      view: __inherit
      create: __inherit
    filter: __noFilter
  UnverifiedPolicyEndorsements:
    permissions:
      view: __inherit
      create: __inherit
    filter: __noFilter
  UnverifiedPolicyLocation:
    permissions:
      view: __inherit
      edit: __inherit
  UnverifiedPolicyLocations:
    permissions:
      view: __inherit
      create: __inherit
    filter: __noFilter
  UnverifiedPropertyItem:
    permissions:
      view: true
      edit: true
  UnverifiedPropertyItems:
    permissions:
      view: true
      create: true
    filter: __noFilter
  UnverifiedRiskUnitCoverage:
    permissions:
      view: __inherit
      edit: __inherit
  UnverifiedRiskUnitCoverages:
    permissions:
      view: __inherit
      create: __inherit
    filter: __noFilter
  UnverifiedTripRiskUnit:
    permissions:
      view: __inherit
      edit: __inherit
  UnverifiedTripRiskUnits:
    permissions:
      view: __inherit
      create: __inherit
    filter: __noFilter
  UnverifiedVehicleRiskUnit:
    permissions:
      view: __inherit
      edit: __inherit
  UnverifiedVehicleRiskUnitCoverage:
    permissions:
      view: __inherit
      edit: __inherit
  UnverifiedVehicleRiskUnitCoverages:
    permissions:
      view: __inherit
      create: __inherit
    filter: __noFilter
  UnverifiedVehicleRiskUnits:
    permissions:
      view: __inherit
      create: __inherit
    filter: __noFilter
  User:
    permissions:
      view: true
      edit: true
      delete: true
  UserAttribute:
    permissions:
      view: true
      edit: true
      delete: true
  UserAttributes:
    permissions:
      view: true
      create: true
    filter: __noFilter
  UserRegion:
    permissions:
      view: true
      edit: true
      delete: true
  UserRegions:
    permissions:
      view: true
      create: true
    filter: __noFilter
  Users:
    permissions:
      view: true
      create: true
    filter: __noFilter
  VehicleDamagePoint:
    permissions:
      view: true
      edit: true
      delete: true
  VehicleDamagePoints:
    permissions:
      view: true
      create: true
    filter: __noFilter
  VehicleIncident:
    permissions:
      view: true
      edit: true
      delete: true
  VehicleRiskUnit:
    permissions:
      view: true
  VehicleRiskUnitCoverage:
    permissions:
      view: __inherit
  VehicleRiskUnitCoverages:
    permissions:
      view: __inherit
    filter: __noFilter
  VehicleRiskUnits:
    permissions:
      view: true
    filter: __noFilter