package rules.Presetup.ClaimPresetup_dir
uses gw.surepath.cc.configuration.timeline.creation.TimelineUtil

@gw.rules.RuleName("CPR10000 - Claim Timeline Creation")
internal class CPR10000ClaimTimelineCreation {
  static function doCondition(claim : entity.Claim) : boolean {
/*start00rule*/
return true
/*end00rule*/
}

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/
TimelineUtil.registerCallback(claim, claim.Bundle) 
/*end00rule*/
  }
}
