swagger: "2.0"
consumes:
- application/json
produces:
- application/json
x-gw-combine:
- gw.core.cc.claim.v1.claim_core-1.0
x-gw-schema-import:
  claims: gw.core.cc.claim.v1.claim_property_core-1.0
paths:
  "/claims/{claimId}/dwelling-incidents":
    parameters:
    - $ref: "#/parameters/claimId"
    get:
      summary: "Retrieve dwelling incidents on a claim"
      description: "Retrieve dwelling incidents on a claim"
      operationId: getDwellingIncidents
      x-gw-extensions:
        childResourceType: DwellingIncident
        operationType: get-collection
        resourceType: ClaimDwellingIncidents
      x-gw-parameter-sets:
      - get-collection
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/DwellingIncidentList"
    post:
      summary: "Create a new dwelling incident"
      description: "Create a new dwelling incident"
      operationId: createClaimDwellingIncident
      x-gw-extensions:
        childResourceType: DwellingIncident
        operationType: post-collection
        resourceType: ClaimDwellingIncidents
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: "#/definitions/DwellingIncidentRequest"
      x-gw-parameter-sets:
      - post-collection
      responses:
        "201":
          description: "Successfully created"
          schema:
            $ref: "#/definitions/DwellingIncidentResponse"
  "/claims/{claimId}/dwelling-incidents/{incidentId}":
    parameters:
    - $ref: "#/parameters/claimId"
    - $ref: "#/parameters/incidentId"
    get:
      summary: "Retrieve a dwelling incident"
      description: "Retrieve a dwelling incident"
      operationId: getDwellingIncident
      x-gw-extensions:
        operationType: get-element
        resourceType: DwellingIncident
      x-gw-parameter-sets:
      - get-element
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/DwellingIncidentResponse"
    patch:
      summary: "Update a dwelling incident"
      description: "Update a dwelling incident"
      operationId: patchDwellingIncident
      x-gw-extensions:
        operationType: patch-element
        resourceType: DwellingIncident
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: "#/definitions/DwellingIncidentRequest"
      x-gw-parameter-sets:
      - patch-element
      responses:
        "200":
          description: "Successfully updated"
          schema:
            $ref: "#/definitions/DwellingIncidentResponse"
    delete:
      summary: "Delete a dwelling incident on the given claim"
      description: "Delete a dwelling incident on the given claim"
      operationId: deleteDwellingIncident
      x-gw-sinceVersion: "1.9.0"
      x-gw-extensions:
        operationType: delete-element
        resourceType: DwellingIncident
      x-gw-parameter-sets:
      - delete-element
      responses:
        "204":
          description: "Successful deletion"
  "/claims/{claimId}/living-expenses-incidents":
    parameters:
    - $ref: "#/parameters/claimId"
    get:
      summary: "Retrieve living expense incidents on a claim"
      description: "Retrieve living expense incidents on a claim"
      operationId: getLivingExpensesIncidents
      x-gw-extensions:
        childResourceType: LivingExpensesIncident
        operationType: get-collection
        resourceType: ClaimLivingExpensesIncidents
      x-gw-parameter-sets:
      - get-collection
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/LivingExpensesIncidentList"
    post:
      summary: "Create a new living expense incident"
      description: "Create a new living expense incident"
      operationId: createClaimLivingExpensesIncident
      x-gw-extensions:
        childResourceType: LivingExpensesIncident
        operationType: post-collection
        resourceType: ClaimLivingExpensesIncidents
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: "#/definitions/LivingExpensesIncidentRequest"
      x-gw-parameter-sets:
      - post-collection
      responses:
        "201":
          description: "Successfully created"
          schema:
            $ref: "#/definitions/LivingExpensesIncidentResponse"
  "/claims/{claimId}/living-expenses-incidents/{incidentId}":
    parameters:
    - $ref: "#/parameters/claimId"
    - $ref: "#/parameters/incidentId"
    get:
      summary: "Retrieve a living expense incident"
      description: "Retrieve a living expense incident"
      operationId: getLivingExpensesIncident
      x-gw-extensions:
        operationType: get-element
        resourceType: LivingExpensesIncident
      x-gw-parameter-sets:
      - get-element
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/LivingExpensesIncidentResponse"
    patch:
      summary: "Update a living expense incident"
      description: "Update a living expense incident"
      operationId: patchLivingExpensesIncident
      x-gw-extensions:
        operationType: patch-element
        resourceType: LivingExpensesIncident
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: "#/definitions/LivingExpensesIncidentRequest"
      x-gw-parameter-sets:
      - patch-element
      responses:
        "200":
          description: "Successfully updated"
          schema:
            $ref: "#/definitions/LivingExpensesIncidentResponse"
    delete:
      summary: "Delete a living expenses incident on the given claim"
      description: "Delete a living expenses incident on the given claim"
      operationId: deleteLivingExpensesIncident
      x-gw-sinceVersion: "1.9.0"
      x-gw-extensions:
        operationType: delete-element
        resourceType: LivingExpensesIncident
      x-gw-parameter-sets:
      - delete-element
      responses:
        "204":
          description: "Successful deletion"
  "/claims/{claimId}/policy/location-based-risk-units":
    parameters:
    - $ref: "#/parameters/claimId"
    get:
      summary: "The location based risk units of a policy associated with a given claim"
      description: "The location based risk units of a policy associated with a given claim"
      operationId: getLocationBasedRiskUnits
      x-gw-extensions:
        childResourceType: LocationBasedRiskUnit
        operationType: get-collection
        resourceType: LocationBasedRiskUnits
      x-gw-parameter-sets:
      - get-collection
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/LocationBasedRiskUnitList"
  "/claims/{claimId}/policy/location-based-risk-units/{locationBasedRiskUnitId}":
    parameters:
    - $ref: "#/parameters/claimId"
    - $ref: "#/parameters/locationBasedRiskUnitId"
    get:
      summary: "Retrieve a location based risk unit"
      description: "Retrieve a location based risk unit"
      operationId: getLocationBasedRiskUnit
      x-gw-extensions:
        operationType: get-element
        resourceType: LocationBasedRiskUnit
      x-gw-parameter-sets:
      - get-element
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/LocationBasedRiskUnitResponse"
  "/claims/{claimId}/policy/location-based-risk-units/{locationBasedRiskUnitId}/coverages":
    parameters:
    - $ref: "#/parameters/claimId"
    - $ref: "#/parameters/locationBasedRiskUnitId"
    get:
      summary: "Retrieves a list of coverages on a location based risk unit"
      description: "Retrieves a list of coverages on a location based risk unit"
      operationId: getLocationBasedRiskUnitCoverages
      x-gw-sinceVersion: "1.4.0"
      x-gw-extensions:
        childResourceType: LocationBasedRiskUnitCoverage
        operationType: get-collection
        resourceType: LocationBasedRiskUnitCoverages
      x-gw-parameter-sets:
      - get-collection
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/PolicyCoverageList"
  "/claims/{claimId}/policy/location-based-risk-units/{locationBasedRiskUnitId}/coverages/{coverageId}":
    parameters:
    - $ref: "#/parameters/claimId"
    - $ref: "#/parameters/locationBasedRiskUnitId"
    - $ref: "#/parameters/coverageId"
    get:
      summary: "Details of a coverage on a location based risk unit"
      description: "Details of a coverage on a location based risk unit"
      operationId: getLocationBasedRiskUnitCoverage
      x-gw-sinceVersion: "1.4.0"
      x-gw-extensions:
        operationType: get-element
        resourceType: LocationBasedRiskUnitCoverage
      x-gw-parameter-sets:
      - get-element
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/PolicyCoverageResponse"
  "/unverified-policies/{policyId}/location-based-risk-units":
    parameters:
    - $ref: "#/parameters/policyId"
    get:
      summary: "Retrieves a list of location based risk units"
      description: "Retrieves a list of location based risk units"
      operationId: getUnverifiedLocationBasedRiskUnits
      x-gw-sinceVersion: "1.2.0"
      x-gw-extensions:
        childResourceType: UnverifiedLocationBasedRiskUnit
        operationType: get-collection
        resourceType: UnverifiedLocationBasedRiskUnits
      x-gw-parameter-sets:
      - get-collection
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/LocationBasedRiskUnitList"
    post:
      summary: "Create a location-based risk unit"
      description: "Create a location-based risk unit"
      operationId: postUnverifiedLocationBasedRiskUnit
      x-gw-sinceVersion: "1.2.0"
      x-gw-extensions:
        childResourceType: UnverifiedLocationBasedRiskUnit
        operationType: post-collection
        resourceType: UnverifiedLocationBasedRiskUnits
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: "#/definitions/LocationBasedRiskUnitRequest"
      x-gw-parameter-sets:
      - post-collection
      responses:
        "201":
          description: "Successful creation"
          schema:
            $ref: "#/definitions/LocationBasedRiskUnitResponse"
  "/unverified-policies/{policyId}/location-based-risk-units/{locationBasedRiskUnitId}":
    parameters:
    - $ref: "#/parameters/policyId"
    - $ref: "#/parameters/locationBasedRiskUnitId"
    get:
      summary: "Get a location based risk unit"
      description: "Get a location based risk unit"
      operationId: getUnverifiedLocationBasedRiskUnit
      x-gw-sinceVersion: "1.2.0"
      x-gw-extensions:
        operationType: get-element
        resourceType: UnverifiedLocationBasedRiskUnit
      x-gw-parameter-sets:
      - get-element
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/LocationBasedRiskUnitResponse"
    patch:
      summary: "Update a location based risk unit"
      description: "Update a location based risk unit"
      operationId: patchUnverifiedLocationBasedRiskUnit
      x-gw-sinceVersion: "1.2.0"
      x-gw-extensions:
        operationType: patch-element
        resourceType: UnverifiedLocationBasedRiskUnit
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: "#/definitions/LocationBasedRiskUnitRequest"
      x-gw-parameter-sets:
      - patch-element
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/LocationBasedRiskUnitResponse"
  "/unverified-policies/{policyId}/location-based-risk-units/{locationBasedRiskUnitId}/coverages":
    parameters:
    - $ref: "#/parameters/policyId"
    - $ref: "#/parameters/locationBasedRiskUnitId"
    get:
      summary: "Retrieves a list of coverages on a location based risk unit"
      description: "Retrieves a list of coverages on a location based risk unit"
      operationId: getUnverifiedLocationBasedRiskUnitCoverages
      x-gw-sinceVersion: "1.2.0"
      x-gw-extensions:
        childResourceType: UnverifiedLocationBasedRiskUnitCoverage
        operationType: get-collection
        resourceType: UnverifiedLocationBasedRiskUnitCoverages
      x-gw-parameter-sets:
      - get-collection
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/UnverifiedPolicyCoverageList"
    post:
      summary: "Create a coverage on a location based risk unit"
      description: "Create a coverage on a location based risk unit"
      operationId: postUnverifiedLocationBasedRiskUnitCoverage
      x-gw-sinceVersion: "1.2.0"
      x-gw-extensions:
        childResourceType: UnverifiedLocationBasedRiskUnitCoverage
        operationType: post-collection
        resourceType: UnverifiedLocationBasedRiskUnitCoverages
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: "#/definitions/UnverifiedPolicyCoverageRequest"
      x-gw-parameter-sets:
      - post-collection
      responses:
        "201":
          description: "Successful creation"
          schema:
            $ref: "#/definitions/UnverifiedPolicyCoverageResponse"
  "/unverified-policies/{policyId}/location-based-risk-units/{locationBasedRiskUnitId}/coverages/{coverageId}":
    parameters:
    - $ref: "#/parameters/policyId"
    - $ref: "#/parameters/locationBasedRiskUnitId"
    - $ref: "#/parameters/coverageId"
    get:
      summary: "Details of a coverage on a location based risk unit"
      description: "Details of a coverage on a location based risk unit"
      operationId: getUnverifiedLocationBasedRiskUnitCoverage
      x-gw-sinceVersion: "1.2.0"
      x-gw-extensions:
        operationType: get-element
        resourceType: UnverifiedLocationBasedRiskUnitCoverage
      x-gw-parameter-sets:
      - get-element
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/UnverifiedPolicyCoverageResponse"
    patch:
      summary: "Update a coverage on a location based risk unit"
      description: "Update a coverage on a location based risk unit"
      operationId: patchUnverifiedLocationBasedRiskUnitCoverage
      x-gw-sinceVersion: "1.2.0"
      x-gw-extensions:
        operationType: patch-element
        resourceType: UnverifiedLocationBasedRiskUnitCoverage
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: "#/definitions/UnverifiedPolicyCoverageRequest"
      x-gw-parameter-sets:
      - patch-element
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/UnverifiedPolicyCoverageResponse"
parameters:
  locationBasedRiskUnitId:
    name: locationBasedRiskUnitId
    in: path
    description: "The identifier for the location based risk unit"
    required: true
    type: string
definitions:
  ClaimRequestInclusions:
    type: object
    properties:
      DwellingIncident:
        type: array
        items:
          $ref: "#/definitions/DwellingIncidentData"
      LivingExpensesIncident:
        type: array
        items:
          $ref: "#/definitions/LivingExpensesIncidentData"
  ClaimResponseInclusions:
    type: object
    properties:
      DwellingIncident:
        type: array
        items:
          $ref: "#/definitions/DwellingIncidentData"
      LivingExpensesIncident:
        type: array
        items:
          $ref: "#/definitions/LivingExpensesIncidentData"
      LocationBasedRiskUnit:
        type: array
        items:
          $ref: "#/definitions/LocationBasedRiskUnitData"
  DwellingIncidentData:
    x-gw-extend:
    - "#/definitions/DataEnvelope"
    required:
    - attributes
    properties:
      attributes:
        $ref: "claims#/definitions/DwellingIncident"
  DwellingIncidentList:
    type: object
    x-gw-extend:
    - "#/definitions/DataListEnvelope"
    properties:
      data:
        type: array
        items:
          $ref: "#/definitions/DwellingIncidentData"
      included:
        $ref: "#/definitions/ClaimResponseInclusions"
  DwellingIncidentRequest:
    type: object
    required:
    - data
    properties:
      data:
        $ref: "#/definitions/DwellingIncidentData"
  DwellingIncidentResponse:
    type: object
    properties:
      data:
        $ref: "#/definitions/DwellingIncidentData"
      included:
        $ref: "#/definitions/ClaimResponseInclusions"
  LivingExpensesIncidentData:
    x-gw-extend:
    - "#/definitions/DataEnvelope"
    required:
    - attributes
    properties:
      attributes:
        $ref: "claims#/definitions/LivingExpensesIncident"
  LivingExpensesIncidentList:
    type: object
    x-gw-extend:
    - "#/definitions/DataListEnvelope"
    properties:
      data:
        type: array
        items:
          $ref: "#/definitions/LivingExpensesIncidentData"
      included:
        $ref: "#/definitions/ClaimResponseInclusions"
  LivingExpensesIncidentRequest:
    type: object
    required:
    - data
    properties:
      data:
        $ref: "#/definitions/LivingExpensesIncidentData"
  LivingExpensesIncidentResponse:
    type: object
    properties:
      data:
        $ref: "#/definitions/LivingExpensesIncidentData"
      included:
        $ref: "#/definitions/ClaimResponseInclusions"
  LocationBasedRiskUnitData:
    x-gw-extend:
    - "#/definitions/DataEnvelope"
    required:
    - attributes
    properties:
      attributes:
        $ref: "claims#/definitions/LocationBasedRiskUnit"
  LocationBasedRiskUnitList:
    type: object
    x-gw-extend:
    - "#/definitions/DataListEnvelope"
    properties:
      data:
        type: array
        items:
          $ref: "#/definitions/LocationBasedRiskUnitData"
  LocationBasedRiskUnitRequest:
    type: object
    required:
    - data
    properties:
      data:
        $ref: "#/definitions/LocationBasedRiskUnitData"
  LocationBasedRiskUnitResponse:
    type: object
    properties:
      data:
        $ref: "#/definitions/LocationBasedRiskUnitData"
      included:
        $ref: "#/definitions/ClaimResponseInclusions"