swagger: "2.0"
consumes:
- application/json
produces:
- application/json
x-gw-combine:
- gw.content.cc.testutil.v1.testutil_content-1.0
x-gw-schema-import:
  testutil: ext.testutil.v1.testutil_ext-1.0
x-gw-apihandlers:
- gw.rest.ext.cc.testutil.v1.TestUtilApiExtHandler
paths: {}