swagger: "2.0"
consumes:
- application/json
produces:
- application/json
x-gw-combine:
- gw.core.cc.common.v1.common_auto_core-1.0
x-gw-schema-import:
  common: ext.common.v1.common_auto_ext-1.0
paths: {}